/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\modelo3DTanque.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshBasicMaterial } from 'three'

export default function Model3DTanque({color}) {
  const { nodes, materials } = useGLTF('/modelo3DTanque.glb')
  const materialEsferaSalida = new MeshBasicMaterial({ color })
  const materialEsferaEntrada = new MeshBasicMaterial({ color })
  return (
    <group dispose={null}>
      <mesh geometry={nodes.Cilindro.geometry} material={materials['Material.001']} position={[-0.047, 1.356, -0.334]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Pala1.geometry} material={materials['default']} position={[0.714, 1.553, -0.325]} rotation={[Math.PI / 2, 0, 0]} scale={[0.127, 0.112, 3.029]} />
      <mesh geometry={nodes.Pala2.geometry} material={materials['default']} position={[-0.77, 1.575, -0.325]} rotation={[Math.PI / 2, 0, 0]} scale={[0.127, 0.112, 3.029]} />
      <mesh geometry={nodes.Esfera.geometry} material={materialEsferaSalida} position={[1.662, 0.586, -0.333]} />
      <mesh geometry={nodes.Esfera001.geometry} material={materialEsferaEntrada} position={[-1.756, 0.586, -0.333]} />
    </group>
  )
}

useGLTF.preload('/modelo3DTanque.glb')
