/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\modelo3DTanque.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/modelo3DTanque.glb')

  const customMaterial = new MeshStandardMaterial({ color: props.color })
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cilindro.geometry} material={customMaterial} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1.757, 1]} />
    </group>
  )
}

useGLTF.preload('/modelo3DTanque.glb')
