/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\modelo3DTanque.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useRef } from 'react'
import { MeshStandardMaterial } from 'three'

export default function Model3DTanque({valvulaEntradastate, valvulaSalidastate, speed=1}) {
  const { nodes, materials } = useGLTF('/modelo3DTanque.glb')
  const Pala1Mesh = useRef()
  const Pala2Mesh = useRef()

  const meshMaterialValvulaSalida = new MeshStandardMaterial({ color: valvulaSalidastate })
  const meshMaterialValvulaEntrada = new MeshStandardMaterial({ color: valvulaEntradastate })

  useFrame(({ clock }) => {
    const elapsedTime = clock.getElapsedTime() * speed

    Pala1Mesh.current.rotation.z = elapsedTime
    Pala2Mesh.current.rotation.z = -elapsedTime
  })

  return (
    <group dispose={null}>
      <mesh geometry={nodes.Tanque.geometry} material={materials['Material.001']} position={[-0.047, 1.356, -0.334]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh ref={Pala1Mesh} geometry={nodes.Pala1.geometry} material={materials['default']} position={[0.714, 1.553, -0.325]} rotation={[Math.PI / 2, 0, 0]} scale={[0.127, 0.112, 3.029]} />
      <mesh ref={Pala2Mesh} geometry={nodes.Pala2.geometry} material={materials['default']} position={[-0.77, 1.575, -0.325]} rotation={[Math.PI / 2, 0, 0]} scale={[0.127, 0.112, 3.029]} />
      <mesh geometry={nodes.ValvulaEntrada.geometry} material={meshMaterialValvulaEntrada} position={[1.591, 0.852, 0.04]} scale={[1, 0.656, 0.656]} />
      <mesh geometry={nodes.ValvulaSalida.geometry} material={meshMaterialValvulaSalida} position={[1.583, 0.852, -0.651]} scale={[1, 0.656, 0.656]} />
    </group>
  )
}

useGLTF.preload('/modelo3DTanque.glb')